n = input('Digite algo:')
print('O tipo primitivo e:', type(n))
print('E sommente espaços:', n.isspace())
print('E um numero', n.isnumeric())
print('E um digito', n.isdigit())
print('E  alfabteico:', n.isalpha())
print('Ele e alphanumerico', n.isalnum())
print('Esta em maiuscula:', n.isupper())
print('Esta em minuscula', n.islower())
print('Esta capitalizada:', n.istitle())
