l = float(input('Qual e a largura da parede: '))
a = float(input('Qual e a altura da parede: '))
ar = ((l*a)/2)
print(f'Sua parede tem {l}x{a} e sua area e {ar}')
print(f'Para pintar a parede sera necessario {ar/2} litros ')